name: shelf_gzip
description: Shelf middleware to GZIP responses
version: 2.0.0
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/shelf_gzip

environment:
  sdk: '>=2.0.0-dev.32 <2.0.0'

dependencies:
  shelf: ">=0.7.0 <0.8.0"

